site_name: Lousa Assurance
site_description: Temporal and epistemic assurance tooling
repo_url: https://github.com/lousa/lousa-assurance
strict: true
nav:
  - Home: index.md
  - ADRs:
      - Overview: docs/adr/README.md
      - Repo standardization: docs/adr/0001-repo-standardization.md
docs_dir: docs
extra_css: []
extra_javascript: []
markdown_extensions:
  - admonition
  - toc:
      permalink: true
