name: lousa-assurance
language: python
package_manager: pip
runtime:
  python: 3.11.8
entrypoints:
  cli: lousa.cli:app
ports: []
service_type: library
owners:
  - team: assurance-platform
    contacts:
      - opensource@lousa.dev
notes:
  structure_contract: "Standardized per Lousa engineering guidelines. Deviations: none."
