[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lousa-assurance-local"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
  "PyYAML>=6.0.1",
  "jsonschema>=4.22.0",
  "pytest>=8.2.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
py-modules = ["calculate_posture"]
