version: 1
formatters:
  jsonfmt:
    format: "%(message)s"
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: jsonfmt
    stream: ext://sys.stdout
loggers:
  lousa:
    level: INFO
    handlers: [stdout]
    propagate: no
root:
  level: WARNING
  handlers: [stdout]
