#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/common.sh"

install_dev_dependencies
"${VENV_PATH}/bin/pip-audit" "$@"
"${VENV_PATH}/bin/bandit" -r src/lousa -ll
"${VENV_PATH}/bin/detect-secrets" scan --baseline .secrets.baseline --all-files --fail-on-unaudited --output /tmp/detect-secrets.json
