name: Assure
on:
  push:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Bootstrap and run pipeline tests
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .
          pip install pytest
          pytest -q
