# SPDX-License-Identifier: MPL-2.0
name: conventional-pr-labels

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
